apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webapp
  namespace: $JOB_BASE_NAME
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: webapp
    spec:
      containers:
      - name: webapp
        image: inventx/k8s:0.2.16
        imagePullPolicy: Always
        env:
        - name: Author
          value: developer
        ports:
        - name: webapp
          containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10 
          timeoutSeconds: 15
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 1
