apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: webapp
    spec:
      containers:
      - name: webapp
        image: inventx/k8s:20180413.113747
        imagePullPolicy: Always
        env:
        - name: Author
          value: developer
        ports:
        - name: webapp
          containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10 
          timeoutSeconds: 15
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 1
