apiVersion: v1
kind: Service
metadata:
  name: webapp
  namespace: $GIT_LOCAL_BRANCH
  labels:
    name: webapp
spec:
  ports:
    - name: webapp
      port: 80    
      targetPort: webapp
  selector:
    name: webapp
